workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.android/build-cache
    environment:
      flutter: 3.19.6  # Conservative stable version for Kotlin compatibility
      xcode: latest
      cocoapods: default
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx8g"
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$FCI_BUILD_DIR/android/local.properties"

      - name: Install Android SDK components
        script: |
          echo "📱 Installing Android SDK components..."
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0" "ndk;26.1.10909125" --channel=3
          echo "🔄 Updating Android SDK..."
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
          echo "✅ Android SDK setup completed"

      - name: Setup Gradle properties for memory
        script: |
          mkdir -p $HOME/.gradle
          echo "org.gradle.jvmargs=-Xmx8g" > $HOME/.gradle/gradle.properties
          echo "org.gradle.daemon=true" >> $HOME/.gradle/gradle.properties
          echo "org.gradle.parallel=true" >> $HOME/.gradle/gradle.properties
          echo "org.gradle.configureondemand=true" >> $HOME/.gradle/gradle.properties

      - name: Force reset Flutter packages (Gemini 2.5 Pro strategy)
        script: |
          echo "🔄 Implementing Gemini 2.5 Pro recommended reset strategy..."
          # 强制清理和重置依赖
          flutter clean
          rm -f pubspec.lock
          flutter pub get
          flutter pub upgrade
          echo "✅ Flutter packages reset completed"
          
      - name: Verify Android embedding configuration
        script: |
          echo "⚙️ Verifying Android embedding v2 configuration..."
          echo "📝 Checking AndroidManifest.xml embedding setting:"
          grep -n "flutterEmbedding" android/app/src/main/AndroidManifest.xml || echo "Embedding setting not found"
          echo "📁 Checking MainActivity structure:"
          find android/app/src -name "MainActivity.*" -type f || echo "MainActivity not found"
          echo "✅ Android embedding verification completed"

      - name: Clean build environment
        script: |
          echo "🧹 Cleaning build environment..."
          flutter clean
          cd android && ./gradlew clean && cd ..
          echo "✅ Build environment cleaned"
          
      - name: Build APK with Flutter (Gemini 2.5 Pro verbose mode)
        script: |
          echo "🚀 Building APK with Gemini 2.5 Pro recommended verbose configuration..."
          echo "📋 Flutter version verification:"
          flutter --version
          echo "📋 Current working directory: $(pwd)"
          
          # Gemini建议的详细构建过程
          echo "🔨 Starting Flutter APK build with verbose logging..."
          flutter build apk --release --verbose
          
          # 检查构建结果
          if [ $? -eq 0 ]; then
            echo "✅ Flutter build command completed successfully"
          else
            echo "❌ Flutter build command failed with exit code $?"
            echo "📋 Build failure - verbose logs above show detailed error information"
            exit 1
          fi
          
      - name: Comprehensive APK search
        script: |
          echo "🔍 Comprehensive APK file search..."
          echo "📁 Current directory: $(pwd)"
          
          # 全系统搜索APK文件
          echo "🔍 Searching for ALL .apk files in current directory tree:"
          find . -name "*.apk" -type f 2>/dev/null || echo "No .apk files found"
          
          # 检查可能的构建输出目录
          echo "📂 Checking possible build directories:"
          for dir in "build/app/outputs/flutter-apk" "build/app/outputs/apk/release" "build/app/outputs/bundle/release" "android/app/build/outputs/apk/release"; do
            if [ -d "$dir" ]; then
              echo "✅ Directory exists: $dir"
              ls -la "$dir"
            else
              echo "❌ Directory not found: $dir"
            fi
          done
          
          # 显示完整的build目录结构
          echo "🗂️ Complete build directory structure:"
          if [ -d "build" ]; then
            find build -type f -name "*.apk" -o -name "*.aab" 2>/dev/null || echo "No APK/AAB files in build directory"
            echo "📁 Build directory tree (first 50 lines):"
            find build -type f | head -50 || echo "Build directory is empty or doesn't exist"
          else
            echo "❌ Build directory doesn't exist!"
          fi
          
          # 检查Android项目结构
          echo "📱 Android build outputs:"
          if [ -d "android" ]; then
            find android -name "*.apk" -type f 2>/dev/null || echo "No APK files in android directory"
          else
            echo "❌ Android directory doesn't exist!"
          fi
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/apk/release/*.apk
      - android/app/build/outputs/apk/release/*.apk
      - build/**/*.apk
      - android/**/*.apk
      - "**/*.apk"

    publishing:
      # android_signing:
      #   keystore: $CM_KEYSTORE
      #   keystore_password: $CM_KEYSTORE_PASSWORD
      #   key_alias: $CM_KEY_ALIAS
      #   key_password: $CM_KEY_ALIAS_PASSWORD
      
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true