workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.android/build-cache
    environment:
      flutter: 3.29.0  # Use specific version with v1 embedding removal
      xcode: latest
      cocoapods: default
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx8g"
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$FCI_BUILD_DIR/android/local.properties"

      - name: Install Android SDK components
        script: |
          echo "📱 Installing Android SDK components..."
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0" "ndk;26.1.10909125" --channel=3
          echo "🔄 Updating Android SDK..."
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update
          echo "✅ Android SDK setup completed"

      - name: Setup Gradle properties for memory
        script: |
          mkdir -p $HOME/.gradle
          echo "org.gradle.jvmargs=-Xmx8g" > $HOME/.gradle/gradle.properties
          echo "org.gradle.daemon=true" >> $HOME/.gradle/gradle.properties
          echo "org.gradle.parallel=true" >> $HOME/.gradle/gradle.properties
          echo "org.gradle.configureondemand=true" >> $HOME/.gradle/gradle.properties

      - name: Get Flutter packages
        script: |
          flutter packages pub get
          
      - name: Force upgrade problematic Android plugins
        script: |
          echo "🔧 Force upgrading Android plugins to latest versions..."
          flutter pub add shared_preferences:^2.5.3 --no-pub
          flutter pub add path_provider:^2.1.5 --no-pub  
          flutter pub add sqflite:^2.4.2 --no-pub
          flutter packages pub get
          echo "✅ Android plugins upgraded successfully"

      - name: Clean build environment
        script: |
          echo "🧹 Cleaning build environment..."
          flutter clean
          cd android && ./gradlew clean && cd ..
          echo "✅ Build environment cleaned"
          
      - name: Build APK with Flutter
        script: |
          echo "🚀 Building APK with enhanced configuration..."
          flutter build apk --release --verbose
          echo "✅ APK build completed"
          
      - name: Verify APK location
        script: |
          echo "🔍 Checking APK file location..."
          find . -name "*.apk" -type f
          ls -la build/app/outputs/flutter-apk/ || echo "Directory not found"
          ls -la build/app/outputs/apk/release/ || echo "Alternative directory not found"
          echo "📁 Build directory structure:"
          find build -name "*.apk" -type f 2>/dev/null || echo "No APK files found in build directory"
          
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/apk/release/*.apk
      - "**/*.apk"

    publishing:
      # android_signing:
      #   keystore: $CM_KEYSTORE
      #   keystore_password: $CM_KEYSTORE_PASSWORD
      #   key_alias: $CM_KEY_ALIAS
      #   key_password: $CM_KEY_ALIAS_PASSWORD
      
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true