workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$FCI_BUILD_DIR/android/local.properties"

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Build APK with Flutter
        script: |
          flutter build apk --release --android-skip-build-dependency-validation
          
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      # android_signing:
      #   keystore: $CM_KEYSTORE
      #   keystore_password: $CM_KEYSTORE_PASSWORD
      #   key_alias: $CM_KEY_ALIAS
      #   key_password: $CM_KEY_ALIAS_PASSWORD
      
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true