workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/.android/build-cache
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        JAVA_TOOL_OPTIONS: "-Xmx8g"
    scripts:
      - name: Set up local properties
        script: |
          echo "flutter.sdk=$FLUTTER_ROOT" > "$FCI_BUILD_DIR/android/local.properties"

      - name: Install Android SDK components
        script: |
          echo "Installing Android SDK components..."
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0" "ndk;26.1.10909125" --channel=3

      - name: Setup Gradle properties for memory
        script: |
          mkdir -p $HOME/.gradle
          echo "org.gradle.jvmargs=-Xmx8g" > $HOME/.gradle/gradle.properties
          echo "org.gradle.daemon=true" >> $HOME/.gradle/gradle.properties
          echo "org.gradle.parallel=true" >> $HOME/.gradle/gradle.properties
          echo "org.gradle.configureondemand=true" >> $HOME/.gradle/gradle.properties

      - name: Get Flutter packages
        script: |
          flutter packages pub get

      - name: Build APK with Flutter
        script: |
          flutter build apk --release
          
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      # android_signing:
      #   keystore: $CM_KEYSTORE
      #   keystore_password: $CM_KEYSTORE_PASSWORD
      #   key_alias: $CM_KEY_ALIAS
      #   key_password: $CM_KEY_ALIAS_PASSWORD
      
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: true